version: '3.8'

networks:
  transcendence:

volumes:
  data:

services:

  # DATABASE #
  db:
    container_name: postgresql
    image: postgres:15-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - transcendence
    env_file:
      - .env
  
  # NGINX #
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - transcendence
    env_file:
      - .env

  # BACK #
  back:
    container_name: back
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8081:8081
      - 8082:8082
      - 8083:8083
    restart: unless-stopped
    networks:
      - transcendence
    depends_on:
      - db
    env_file:
      - .env

# FRONT #
  front:
    container_name : front
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - transcendence
    depends_on:
      - back
    env_file:
      - .env