version: '3.8'
services:
  dev-db:
    image: postgres:15-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - ft_transcendence
  test-db:
    image: postgres:15-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - ft_transcendence
networks:
  ft_transcendence: