import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

import '../../styles/globals.css'
import HomeButton from '../../components/HomeButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <HomeButton></HomeButton>
        <div>SOCIAL MENU</div>
        {children}
      </body>
    </html>
  )
}
